### ISSUE TITLE
register Issue 

### ISSUE THREAD

**Issue by Jimbonio** [sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library#11]
Hi,

maybe there is an issue in 'sfe_ism330dhcx_defs.h' compared to datasheet:

ISM_XL_BATCH_AT_6667Hz should be 0x0A instead 0x010 which would be the right decimal value. 
Same on ISM_XL_BATCH_6Hz5 and for Gyro.

Best regards,

Patrick

**Comment by edspark** [comment]
Yep you're totally right, fixed [here](https://github.com/sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library/commit/7a56354c542a81012ae141e78e43c2609c9f20fa).
