### ISSUE TITLE
Add Function to Link Watermark and batch counter to interrupt

### ISSUE THREAD

**Issue by Jimbonio** [sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library#12]
Hi,

is it possible to implement a function in the lib to link FIFO threshold interrupt or Batch counter (FIFO COUNTER_BDR_IA) to Interrupt? (Setting bits in INT1_CTRL and INT1_CTRL registers)

Or maybe it is already and I don't find it? :)

Best regards,

Patrick

**Comment by edspark** [comment]
Yeah, it does not exist! Give me a business day or two to get that added.

**Comment by edspark** [comment]
Added two new functions listed below: 
```c
    bool setFIFOThresholdInt1(bool enable);
    bool setBatchCounterInt1(bool enable);
```
Let me know if that works for you, closing this out.
