### ISSUE TITLE
Clash with TMF882X Library (class QwI2C)

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library#6]
Please see:

https://github.com/sparkfun/SparkFun_Qwiic_TMF882X_Arduino_Library/issues/3

**Comment by edspark** [comment]
I'd be happy to rename this classes for this library's bus drivers. I'll change it later this afternoon if there's no objection.

**Comment by PaulZC** [comment]
Thanks! The immediate problem is solved - thanks to some nifty coding in the TMF882X lib. But it would be a good idea to add the same fix here as I suspect we’ll want to use QwI2C many more times in the future…

**Comment by kirk-sfe** [comment]
Elias - you can just copy what I did on the TMF882X - use a namespace. It's fairly straightforward - just copy what I did - wrap the QwI2C header and cpp implementation with a namespace statement, and where the QwI2C type is declared, just add the name of the namespace to the object declaration ( QwI2C -> sfe_ISM330DHCX::QwI2C) .

**Comment by edspark** [comment]
Easy enough, added and published in a release.

**Comment by PaulZC** [comment]
Excellent - thank you!
